/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lsFQE0TsXde
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"

export function Cafirm() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center bg-background shadow">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <BriefcaseIcon className="h-6 w-6 text-primary" />
          <span className="text-xl font-bold text-foreground ml-2">Acme Chartered Accountants</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-foreground"
            prefetch={false}
          >
            Services
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-foreground"
            prefetch={false}
          >
            Team
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-foreground"
            prefetch={false}
          >
            Testimonials
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-foreground"
            prefetch={false}
          >
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-20 md:py-32 lg:py-40 bg-gradient-to-r from-primary to-primary/80">
          <div className="container px-4 md:px-6 flex flex-col items-center text-center space-y-6 animate-fade-in">
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-primary-foreground">
              Trusted Accounting Solutions
            </h1>
            <p className="text-lg md:text-xl lg:text-2xl text-primary-foreground max-w-3xl">
              Acme Chartered Accountants provides comprehensive financial services to businesses of all sizes. Trust our
              expertise to navigate the complexities of accounting and taxation.
            </p>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 animate-fade-in-up"
              prefetch={false}
            >
              Get in Touch
            </Link>
          </div>
        </section>
        <section id="services" className="w-full py-20 md:py-32 lg:py-40">
          <div className="container px-4 md:px-6 flex flex-col items-center space-y-8 animate-fade-in">
            <div className="text-center space-y-4">
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground">Our Services</h2>
              <p className="text-lg md:text-xl lg:text-2xl text-muted-foreground max-w-3xl">
                Acme Chartered Accountants offers a wide range of financial services to help your business thrive.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 w-full">
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up">
                <ActivityIcon className="h-12 w-12 text-primary" />
                <h3 className="text-xl font-bold text-foreground mt-4">Accounting</h3>
                <p className="text-muted-foreground mt-2">
                  Accurate financial record-keeping and reporting to ensure compliance and informed decision-making.
                </p>
              </div>
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up delay-100">
                <CurrencyIcon className="h-12 w-12 text-primary" />
                <h3 className="text-xl font-bold text-foreground mt-4">Tax Planning</h3>
                <p className="text-muted-foreground mt-2">
                  Comprehensive tax services to minimize your tax liability and ensure compliance with all relevant
                  regulations.
                </p>
              </div>
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up delay-200">
                <CheckIcon className="h-12 w-12 text-primary" />
                <h3 className="text-xl font-bold text-foreground mt-4">Auditing</h3>
                <p className="text-muted-foreground mt-2">
                  Thorough auditing services to provide assurance and identify areas for improvement in your financial
                  processes.
                </p>
              </div>
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up delay-300">
                <ConciergeBellIcon className="h-12 w-12 text-primary" />
                <h3 className="text-xl font-bold text-foreground mt-4">Consulting</h3>
                <p className="text-muted-foreground mt-2">
                  Strategic financial consulting to help you make informed decisions and achieve your business goals.
                </p>
              </div>
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up delay-400">
                <FlagIcon className="h-12 w-12 text-primary" />
                <h3 className="text-xl font-bold text-foreground mt-4">Advisory</h3>
                <p className="text-muted-foreground mt-2">
                  Personalized advisory services to guide you through complex financial situations and ensure your
                  long-term success.
                </p>
              </div>
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up delay-500">
                <CompassIcon className="h-12 w-12 text-primary" />
                <h3 className="text-xl font-bold text-foreground mt-4">Compliance</h3>
                <p className="text-muted-foreground mt-2">
                  Ensure your business remains compliant with all relevant financial regulations and reporting
                  requirements.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section id="team" className="w-full py-20 md:py-32 lg:py-40 bg-muted">
          <div className="container px-4 md:px-6 flex flex-col items-center space-y-8 animate-fade-in">
            <div className="text-center space-y-4">
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground">Meet Our Team</h2>
              <p className="text-lg md:text-xl lg:text-2xl text-muted-foreground max-w-3xl">
                Our team of experienced chartered accountants is dedicated to providing exceptional service to our
                clients.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 w-full">
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up">
                <Avatar className="w-20 h-20">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <h3 className="text-xl font-bold text-foreground mt-4">John Doe</h3>
                <p className="text-muted-foreground mt-2">Chartered Accountant, CPA</p>
                <p className="text-muted-foreground mt-2">15+ years of experience</p>
              </div>
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up delay-100">
                <Avatar className="w-20 h-20">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JL</AvatarFallback>
                </Avatar>
                <h3 className="text-xl font-bold text-foreground mt-4">Jane Lee</h3>
                <p className="text-muted-foreground mt-2">Chartered Accountant, CPA</p>
                <p className="text-muted-foreground mt-2">10+ years of experience</p>
              </div>
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up delay-200">
                <Avatar className="w-20 h-20">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>SM</AvatarFallback>
                </Avatar>
                <h3 className="text-xl font-bold text-foreground mt-4">Sarah Miller</h3>
                <p className="text-muted-foreground mt-2">Chartered Accountant, CPA</p>
                <p className="text-muted-foreground mt-2">8+ years of experience</p>
              </div>
            </div>
          </div>
        </section>
        <section id="testimonials" className="w-full py-20 md:py-32 lg:py-40">
          <div className="container px-4 md:px-6 flex flex-col items-center space-y-8 animate-fade-in">
            <div className="text-center space-y-4">
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground">What Our Clients Say</h2>
              <p className="text-lg md:text-xl lg:text-2xl text-muted-foreground max-w-3xl">
                Hear from our satisfied clients about their experience working with Acme Chartered Accountants.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 w-full">
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up">
                <blockquote className="flex flex-col justify-between h-full">
                  <div>
                    <QuoteIcon className="h-8 w-8 text-primary" />
                    <p className="text-foreground mt-4">
                      "Acme Chartered Accountants has been an invaluable\n partner for our business. Their expertise and
                      attention\n to detail have been instrumental in our success."
                    </p>
                  </div>
                  <div className="flex items-center mt-6">
                    <Avatar className="w-10 h-10 mr-4">
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="text-foreground font-bold">John Doe, CEO</p>
                      <p className="text-muted-foreground">Acme Inc.</p>
                    </div>
                  </div>
                </blockquote>
              </div>
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up delay-100">
                <blockquote className="flex flex-col justify-between h-full">
                  <div>
                    <QuoteIcon className="h-8 w-8 text-primary" />
                    <p className="text-foreground mt-4">
                      "Working with Acme Chartered Accountants has been a\n game-changer for our business. Their
                      proactive approach\n and attention to detail have helped us navigate the\n complexities of
                      accounting and taxation."
                    </p>
                  </div>
                  <div className="flex items-center mt-6">
                    <Avatar className="w-10 h-10 mr-4">
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JL</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="text-foreground font-bold">Jane Lee, CFO</p>
                      <p className="text-muted-foreground">Acme Corp.</p>
                    </div>
                  </div>
                </blockquote>
              </div>
              <div className="bg-background rounded-lg shadow p-6 animate-fade-in-up delay-200">
                <blockquote className="flex flex-col justify-between h-full">
                  <div>
                    <QuoteIcon className="h-8 w-8 text-primary" />
                    <p className="text-foreground mt-4">
                      "Acme Chartered Accountants has been a trusted partner\n for our business. Their expertise and
                      personalized\n approach have been invaluable in helping us achieve our\n financial goals."
                    </p>
                  </div>
                  <div className="flex items-center mt-6">
                    <Avatar className="w-10 h-10 mr-4">
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>SM</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="text-foreground font-bold">Sarah Miller, CFO</p>
                      <p className="text-muted-foreground">Acme LLC.</p>
                    </div>
                  </div>
                </blockquote>
              </div>
            </div>
          </div>
        </section>
        <section id="contact" className="w-full py-20 md:py-32 lg:py-40 bg-muted">
          <div className="container px-4 md:px-6 flex flex-col items-center space-y-8 animate-fade-in">
            <div className="text-center space-y-4">
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground">Get in Touch</h2>
              <p className="text-lg md:text-xl lg:text-2xl text-muted-foreground max-w-3xl">
                Contact us today to learn how Acme Chartered Accountants can help your business succeed.
              </p>
            </div>
            <form className="bg-background rounded-lg shadow p-6 w-full max-w-md animate-fade-in-up">
              <div className="grid gap-4">
                <Input type="text" placeholder="Name" className="w-full" />
                <Input type="email" placeholder="Email" className="w-full" />
                <Textarea placeholder="Message" className="w-full" />
                <Button type="submit" className="w-full" />
              </div>
            </form>
          </div>
        </section>
      </main>
    </div>
  )
}

function ActivityIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2" />
    </svg>
  )
}


function BriefcaseIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}


function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function CompassIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" />
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}


function ConciergeBellIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 20a1 1 0 0 1-1-1v-1a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v1a1 1 0 0 1-1 1Z" />
      <path d="M20 16a8 8 0 1 0-16 0" />
      <path d="M12 4v4" />
      <path d="M10 4h4" />
    </svg>
  )
}


function CurrencyIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="8" />
      <line x1="3" x2="6" y1="3" y2="6" />
      <line x1="21" x2="18" y1="3" y2="6" />
      <line x1="3" x2="6" y1="21" y2="18" />
      <line x1="21" x2="18" y1="21" y2="18" />
    </svg>
  )
}


function FlagIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}


function QuoteIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 21c3 0 7-1 7-8V5c0-1.25-.756-2.017-2-2H4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 2 2 1 0 1 0 1 1v1c0 1-1 2-2 2s-1 .008-1 1.031V20c0 1 0 1 1 1z" />
      <path d="M15 21c3 0 7-1 7-8V5c0-1.25-.757-2.017-2-2h-4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 2 2h.75c0 2.25.25 4-2.75 4v3c0 1 0 1 1 1z" />
    </svg>
  )
}
